# Generated by Django 3.2.8 on 2025-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_status',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
