# Generated by Django 3.2.8 on 2025-05-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20250510_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='送餐地址'),
        ),
    ]
