# Generated by Django 3.2.8 on 2025-05-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20250510_1431'),
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False, verbose_name='偏好编号')),
                ('preference_type', models.CharField(choices=[('favorite', '收藏'), ('blocked', '拉黑')], max_length=10, verbose_name='偏好类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='顾客')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dish', verbose_name='菜品')),
            ],
            options={
                'verbose_name': '菜品偏好',
                'verbose_name_plural': '菜品偏好',
                'db_table': 'dish_preference',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'dish', 'preference_type')},
            },
        ),
    ]
