# Generated by Django 3.2.8 on 2025-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dishpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='热量(千卡)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='碳水化合物(克)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='脂肪(克)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_spicy',
            field=models.BooleanField(default=False, verbose_name='是否辣'),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='蛋白质(克)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='taste',
            field=models.CharField(choices=[('清淡', '清淡'), ('适中', '适中'), ('重口味', '重口味')], default='适中', max_length=10, verbose_name='口味'),
        ),
    ]
