# Generated by Django 3.2.8 on 2025-05-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='manager',
        ),
    ]
