# Generated by Django 3.2.8 on 2025-05-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_remove_shop_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='sanitation_level',
        ),
    ]
